name = "subsidy-app"
compatibility_date = "2024-01-01"

[vars]
STRIPE_PUBLIC_KEY = "pk_live_51JT6BfH6PyDypRN5lqNIrShGcT4LYB33Yzwa5sfBdVSuEirL6AgxNnAsCaAFOvuFJabwTfkiJeocblEDO3BzN7pP00vWjHVYlq"
# STRIPE_SECRET_KEY should be set as secret: wrangler secret put STRIPE_SECRET_KEY
